a=int(input("Digite um número\n"))
b=int(input("Digite mais um número\n"))
soma=float(a+b)
resta=float(a-b)
divisao=float(a/b)
multiplica=float(a*b)
print(f'A soma deles é {soma};')
print(f'A subtração deles é {resta};')
print(f'A divisão deles é {divisao};')
print(f'E a multiplicação deles é {multiplica};')
